apiVersion: v1
description: Automatically requests certificates from Let's Encrypt
engine: gotpl
keywords:
- kube-lego
- letsencrypt
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
name: kube-lego
sources:
- https://gitlab.com/charts/helm.gitlab.io
version: 0.3.0
