version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Install Python deps
          command: |
            echo "nothing to do in this branch"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
