# This is an example values.yaml. It shows how to configure cert manager
# Commented out settings are for setting a custom wild card certificate instead of cert-manager
certmanager-issuer:
  email: me@example.com
  # install: false
# global:
#   ingress:
#     configureCertmanager: false
#     tls:
#       secretName: my-wild-card-certificate

