image:
  repository: redis
  tag: '3.2.5'
  pullPolicy: 'IfNotPresent'
service:
  name: redis
  type: ClusterIP
  externalPort: 6379
  internalPort: 6379
  clusterIP: '0.0.0.0'
replicas: 1
# define some sane resource requests and limitations
resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 1024Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Chart operation controls
enabled: false

# Configuration items
timeout: 60
tcpKeepalive: 300
loglevel: "notice"
password:
  secret: gitlab-redis
  key: redis-password
# Configure persistence for Redis instance
persistence:
  # Configure the disk used for persistence.
  # - if not configured, it will use an ephemeral `emptyDir`
  #   persist for the lifetime of the `Pod`, in the event of
  #   a container restart.
  disk:
    # use a PVC, by name
    persistentVolumeClaim:
  # Configure save points
  # https://redis.io/topics/persistence
  # - time: every X seconds
  # - writes: if at least Y keys have changed
  # If this is intentionally empty, persistence will be disabled!
  save:
    - time: 60
      writes: 1000
    - time: 300
      writes: 10
    - time: 900
      writes: 1
