apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  generate-secrets: |
{{ include (print $.Template.BasePath "/_generate_secrets.sh") . | indent 4 }}
