apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "shared-secrets.jobname" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      restartPolicy: Never
{{- include "pullsecrets" .Values.image | indent 6}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['/bin/bash', '/scripts/generate-secrets']
          {{ template "gitlab.imagePullPolicy" . }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: {{ template "fullname" . }}
